// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

// A valid token for your 1Password Connect API. Can also be sourced from OP_CONNECT_TOKEN.
func GetToken(ctx *pulumi.Context) string {
	return config.Get(ctx, "onepassword:token")
}

// The HTTP(S) URL where your 1Password Connect API can be found. Must be provided through the the OP_CONNECT_HOST
// environment variable if this attribute is not set.
func GetUrl(ctx *pulumi.Context) string {
	return config.Get(ctx, "onepassword:url")
}
