// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Onepassword.Outputs
{

    [OutputType]
    public sealed class ItemSectionField
    {
        public readonly string? Id;
        public readonly string Label;
        /// <summary>
        /// Password for this item.
        /// </summary>
        public readonly Outputs.ItemSectionFieldPasswordRecipe? PasswordRecipe;
        public readonly string? Purpose;
        /// <summary>
        /// (Only applies to the database category) The type of database. One of ["db2" "filemaker" "msaccess" "mssql" "mysql" "oracle" "postgresql" "sqlite" "other"]
        /// </summary>
        public readonly string? Type;
        public readonly string? Value;

        [OutputConstructor]
        private ItemSectionField(
            string? id,

            string label,

            Outputs.ItemSectionFieldPasswordRecipe? passwordRecipe,

            string? purpose,

            string? type,

            string? value)
        {
            Id = id;
            Label = label;
            PasswordRecipe = passwordRecipe;
            Purpose = purpose;
            Type = type;
            Value = value;
        }
    }
}
