// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "../types";

export interface ItemPasswordRecipe {
    /**
     * Use digits [0-9] when generating the password.
     */
    digits?: pulumi.Input<boolean>;
    /**
     * The length of the password to be generated.
     */
    length?: pulumi.Input<number>;
    /**
     * Use letters [a-zA-Z] when generating the password.
     */
    letters?: pulumi.Input<boolean>;
    /**
     * Use symbols [!@.-_*] when generating the password.
     */
    symbols?: pulumi.Input<boolean>;
}

export interface ItemSection {
    /**
     * A list of custom fields in the section.
     */
    fields?: pulumi.Input<pulumi.Input<inputs.ItemSectionField>[]>;
    /**
     * A unique identifier for the section.
     */
    id?: pulumi.Input<string>;
    /**
     * The label for the section.
     */
    label: pulumi.Input<string>;
}

export interface ItemSectionField {
    id?: pulumi.Input<string>;
    label: pulumi.Input<string>;
    /**
     * Password for this item.
     */
    passwordRecipe?: pulumi.Input<inputs.ItemSectionFieldPasswordRecipe>;
    purpose?: pulumi.Input<string>;
    /**
     * (Only applies to the database category) The type of database. One of ["db2" "filemaker" "msaccess" "mssql" "mysql" "oracle" "postgresql" "sqlite" "other"]
     */
    type?: pulumi.Input<string>;
    value?: pulumi.Input<string>;
}

export interface ItemSectionFieldPasswordRecipe {
    /**
     * Use digits [0-9] when generating the password.
     */
    digits?: pulumi.Input<boolean>;
    /**
     * The length of the password to be generated.
     */
    length?: pulumi.Input<number>;
    /**
     * Use letters [a-zA-Z] when generating the password.
     */
    letters?: pulumi.Input<boolean>;
    /**
     * Use symbols [!@.-_*] when generating the password.
     */
    symbols?: pulumi.Input<boolean>;
}
